import Vue from 'vue'
import VueRouter from 'vue-router'
Vue.use(VueRouter)

/*
  Avoid lazy loading while in dev mode
  to benefit from HMR
 */
function load (name) {
  return require('components/' + name + '.vue')
}

let routes = {
  '/': {component: load('index')},
  '/play': {
    component: load('play/layout-play'),
    subRoutes: {
      '/news': {component: load('play/news'),
   name: 'News',
   title: 'News'},
      '/news-single': {component: load('play/news-single'),
   name: 'News',
   title: 'News'},
      '/news-add': {component: load('play/news-add'),
   name: 'Add News',
   title: 'Add News'},
      '/messages': {component: load('play/messages'),
   name: 'Messages',
   title: 'Messages'},
      '/news2': {component: load('play/news2'),
   name: 'News 2',
   title: 'News2'},
      '/timetable': {component: load('play/timetable'),
   name: 'Timetable',
   title: 'Timetable'},
      '/timetable-edit': {component: load('play/timetable-edit'),
   name: 'Timetable',
   title: 'Timetable'},
      '/quiz': {component: load('play/quiz'),
   name: 'Quiz',
   title: 'Quiz'},
      '/quiz-single': {component: load('play/quiz-single'),
   name: 'Quiz',
   title: 'Quiz'},
      '/quizzes': {component: load('play/quizzes'),
   name: 'Quizzes',
   title: 'Quizzes'},
      '/surveys': {component: load('play/surveys'),
   name: 'Surveys',
   title: 'Surveys'},
      '/survey-add': {component: load('play/survey-add'),
   name: 'Ceate Survey',
   title: 'Create Survey'},
      '/chat': {component: load('play/chat'),
   name: 'Chat',
   title: 'Chat'},
      '/profile': {component: load('play/profile'),
   name: 'Profile',
   title: 'Profile'},
      '/user-add': {component: load('play/user-add'),
   name: 'Add User',
   title: 'Add User'},
      '/news3': {component: load('play/news3'),
   name: 'News3',
   title: 'News3'},
      '/calendar': {component: load('play/calendar'),
   name: 'Calendar',
   title: 'Calendar'},
      '/event': {component: load('play/event'),
   name: 'Event',
   title: 'Event'},
      '/event-add': {component: load('play/event-add'),
   name: 'Add Event',
   title: 'Add Event'},
      '/test': {component: load('play/test'),
   name: 'Test',
   title: 'Test'},
      '/attendance': {component: load('play/attendance'),
   name: 'Attendance Statistics',
   title: 'Attendance Statistics'},
      '/attendance-full': {component: load('play/attendance-full'),
   name: 'Attendance Report',
   title: 'Attendance Report'},
      '/attendance-entry': {component: load('play/attendance-entry'),
   name: 'Enter Attendance',
   title: 'Enter Attendance'},
      '/attendance-leave': {component: load('play/attendance-leave'),
   name: 'Enter Leave',
   title: 'Enter Leave'},
      '/attendance-report': {component: load('play/attendance-report'),
   name: 'Attendance Report',
   title: 'Attendance Report'},
      '/attendance-permissions': {component: load('play/attendance-permissions'),
   name: 'Enter Permissions',
   title: 'Enter Permissions'},
      '/curriculum': {component: load('play/curriculum'),
   name: 'Curriculum',
   title: 'CurricClum'},
      '/subject': {component: load('play/subject'),
   name: 'Subject',
   title: 'Subject'},
      '/report': {component: load('play/report'),
   name: 'Report',
   title: 'Report'},
      '/lesson': {component: load('play/lesson'),
   name: 'Lesson',
   title: 'Lesson'},
      '/lesson2': {component: load('play/lesson2'),
   name: 'Lesson',
   title: 'Lesson'},
      '/lesson-edit': {component: load('play/lesson-edit'),
   name: 'Edit Lesson',
   title: 'Edit Lesson'},
      '/subject-add': {component: load('play/subject-add'),
   name: 'Add in Subject',
   title: 'Add in Subject'},
      '/homework': {component: load('play/homework'),
   name: 'Homework',
   title: 'Homework'},
      '/classwork': {component: load('play/classwork'),
   name: 'Classwork',
   title: 'Classwork'},
      '/homework-single': {component: load('play/homework-single'),
   name: 'Homework',
   title: 'Homework'},
      '/homework-add': {component: load('play/homework-add'),
   name: 'Add Homework',
   title: 'Add Homework'},
      '/groups': {component: load('play/groups'),
   name: 'Manage Groups',
   title: 'Manage Groups'},
      '/contacts': {component: load('play/contacts'),
   name: 'Contacts',
   title: 'Contacts'},
      '/timetable-teacher': {component: load('play/timetable-teacher'),
   name: 'Timetable',
   title: 'Timetable'},
      '/groups-add': {component: load('play/groups-add'),
   name: 'Create Group',
   title: 'Create Group'},
      '/groups-edit': {component: load('play/groups-edit'),
   name: 'Edit Group',
   title: 'Edit Group'}
}
  },
  '*': {
    component: load('error404')
  }
}

let router = new VueRouter()

router.map(routes)
export default router
